- name: Update remote config file
  hosts: 
  - aws_ec2_master
  gather_facts: true
  tasks:
  - name: Copy file 1
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/appweb-deployment.yaml
      dest: /home/ubuntu/appweb-deployment.yaml
     # remote_src: true
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy file 2
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/appweb-service.yaml
      dest: /home/ubuntu/appweb-service.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy file 3
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/database-deployment.yaml
      dest: /home/ubuntu/database-deployment.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy file 4
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/database-service.yaml
      dest: /home/ubuntu/database-service.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy file 5
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/ingress.yaml
      dest: /home/ubuntu/ingress.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

- hosts: 
   - aws_ec2_master
  become: true
  gather_facts: true
  tasks:
    - name: Apply new settings
      shell: |
            kubectl apply -f /home/ubuntu/appweb-deployment.yaml
            kubectl apply -f /home/ubuntu/appweb-service.yaml
            kubectl apply -f /home/ubuntu/database-deployment.yaml
            kubectl apply -f /home/ubuntu/database-service.yaml
            kubectl apply -f /home/ubuntu/ingress.yaml
            apt install awscli -y
        
    - name: Login into AWS ECR
      command: "aws ecr get-login-password --region us-west-2"
      register: command_output
    - set_fact:
        password: "{{ command_output.stdout }}"
   
    - name: Verifying var 
      set_fact:
        dbaccount: "{{groups['aws_ec2_master'] | map('extract',hostvars,'aws_account') | list | join(',')}}"
    - name: Verifying var 
      debug:
        msg: "{{dbaccount}} ee {{password}}"
    - name: Configure ECR Credentials to Kubernetes 
      shell: |
            kubectl delete secret regcred
            kubectl create secret docker-registry regcred \
            --docker-server={{ dbaccount }}.dkr.ecr.us-west-2.amazonaws.com \
            --docker-username=AWS \
            --docker-password=={{password}} \
            --docker-email={{dbaccount}}
            
    - name: Update image appweb
      command: "kubectl set image deployment/appweb-deployment appweb={{dbaccount}}.dkr.ecr.us-west-2.amazonaws.com/webapp:latest"

    - name: Update image database
      command: "kubectl set image deployment/database-deployment database={{dbaccount}}.dkr.ecr.us-west-2.amazonaws.com/database:latest"
