- name: Update remote config file
  hosts: aws_ec2_master
  gather_facts: true
  become: true
  tasks:
    - name: Login into AWS ECR
      command: "aws ecr get-login-password --region us-west-2"
      register: command_output
    - set_fact:
        password: "{{ command_output.stdout }}"
   
    - name: Verifying var 
      set_fact:
        dbaccount: "{{groups['aws_ec2_master'] | map('extract',hostvars,'aws_account') | list | join(',')}}"
    - name: Verifying var 
      debug:
        msg: "{{dbaccount}} ee {{password}}"
    - name: Configure ECR Credentials to Kubernetes 
      command: "kubectl create secret docker-registry regcred --docker-server={{dbaccount}}.dkr.ecr.us-west-2.amazonaws.com --docker-username=AWS --docker-password={{ password }} --docker-email=cloud_user"
            
    - name: Update image appweb
      command: "kubectl set image deployment/appweb-deployment appweb={{dbaccount}}.dkr.ecr.us-west-2.amazonaws.com/webapp:latest"

    - name: Update image database
      command: "kubectl set image deployment/database-deployment database={{dbaccount}}.dkr.ecr.us-west-2.amazonaws.com/database:latest"

    - name: Rescale to force deploy teste
      shell: |
            kubectl scale --replicas=0 deployment appweb-deployment && kubectl scale --replicas=2 deployment appweb-deployment 
            kubectl scale --replicas=0 deployment database-deployment && kubectl scale --replicas=2 deployment database-deployment

    