- name: Update remote config file
  hosts: 
  - aws_ec2_master
  gather_facts: true
  become: true
  tasks:
  - name: Copy file 1
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/appweb-deployment.yaml
      dest: /home/ubuntu/appweb-deployment.yaml
     # remote_src: true
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy file 2
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/appweb-service.yaml
      dest: /home/ubuntu/appweb-service.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy file 3
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/database-deployment.yaml
      dest: /home/ubuntu/database-deployment.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy file 4
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/database-service.yaml
      dest: /home/ubuntu/database-service.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

  - name: Copy file 5
    ansible.builtin.copy:
      src: /home/renancoradini/projetos/kubernetes-cka/kubernetes/ingress.yaml
      dest: /home/ubuntu/ingress.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

- hosts: 
   - aws_ec2_master
  become: true
  gather_facts: true
  tasks:
    - name: Apply new settings
      shell: |
            kubectl apply -f /home/ubuntu/appweb-deployment.yaml
            kubectl apply -f /home/ubuntu/appweb-service.yaml
            kubectl apply -f /home/ubuntu/database-deployment.yaml
            kubectl apply -f /home/ubuntu/database-service.yaml
            apt install awscli -y