apiVersion: apps/v1
kind: Deployment
metadata:
  name: appteste-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appteste
  template:
    metadata:
      labels:
        app: appteste
    spec:
      containers:
      - name: appteste
        image: 315431037525.dkr.ecr.us-west-2.amazonaws.com/apptestev4:latest
        resources:
          limits:
            memory: "384Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred