name: docker-build-pushs

on:
  workflow_call:

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.6.0
 

    - name: Build Apptest - AWS Build image and push to ECR
      uses: appleboy/docker-ecr-action@v0.0.3
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-2
        repo: webapp
        tags: latest
        dockerfile: apptest/Dockerfile
        context: apptest/

    - name: Build postgres - AWS Build image and push to ECR
      uses: appleboy/docker-ecr-action@v0.0.3
      with:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-2
        repo: database
        tags: latest
        dockerfile: postgres/Dockerfile
        context: postgres/